name: kustomize-diff

on:
  workflow_call:
    inputs:
      kustomization:
        description: glob patterns to kustomization.yaml
        type: string
        required: true
      write-individual-files:
        description: set true to write individual files (optional)
        type: boolean
      token:
        description: GitHub token (optional)
        type: string
        default: ${{ secrets.GITHUB_TOKEN }}

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/hide-comment-action@v1
        with:
          token: ${{ inputs.token }}
          ends-with: |
            <!-- kustomize-action -->
            <!-- diff-action -->

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: head
      - uses: int128/kustomize-action@v1
        id: kustomize-head
        with:
          token: ${{ inputs.token }}
          base-directory: head
          write-individual-files: ${{ inputs.write-individual-files }}
          kustomization: ${{ inputs.kustomization }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: base
      - uses: int128/kustomize-action@v1
        id: kustomize-base
        with:
          token: ${{ inputs.token }}
          base-directory: base
          write-individual-files: ${{ inputs.write-individual-files }}
          kustomization: ${{ inputs.kustomization }}
          ignore-kustomize-error: true

      - uses: int128/diff-action@v1
        with:
          token: ${{ inputs.token }}
          base: ${{ steps.kustomize-base.outputs.directory }}
          head: ${{ steps.kustomize-head.outputs.directory }}
